#  numpy.random Package Investigation¶
### This is a Solution to the first assessment on Programming for Data Analysis¶
### Author: Francis Adepoju (G00364694)¶ using my github account dewaledr
#### Start Date: October 12, 2018
### Tasks in this assignment:
1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.

##### Installation Instructions:¶
- It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up. It can also be installed onto existing suystem with: conda install numpy

###### Once you've installed NumPy you can import it as a library:  Import numpy as np


# 1. NumPy¶
NumPy (or Numpy) is a Linear Algebra Library for Python. Numpy is incredibly fast, as it has bindings to C libraries. NumPy's arrays are more compact than Python lists -- a list of lists as you describe, in Python, would take at least 20 MB or so, while a NumPy 3D array with single-precision floats in the cells would fit in 4 MB. Access in reading and writing items is also faster with NumPy [1].
NumPy is the fundamental package for scientific computing with Python. It contains among other things: a powerful N-dimensional array object sophisticated (broadcasting) functions tools for integrating C/C++ and Fortran code useful linear algebra, Fourier transform, and random number capabilities Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can also be defined.
[2].

Broadcasting is the term used to describe the implicit element-by-element behavior of operations; generally speaking, in NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast. 
For example  a and b could be multidimensional arrays of the same shape, or a scalar and an array, or even two arrays of with different shapes, provided that the smaller array is “expandable” to the shape of the larger in such a way that the resulting broadcast is unambiguous. For detailed “rules” of broadcasting see numpy.doc.broadcasting.
NumPy fully supports an object-oriented approach, starting, once again, with ndarray. For example, ndarray is a class, possessing numerous methods and attributes. Many of its methods mirror functions in the outer-most NumPy namespace, giving the programmer complete freedom to code in whichever paradigm she prefers and/or which seems most appropriate to the task at hand. 
[3]. 

#### Numpy has many built-in functions and capabilities. In this notebook, I will focus on some of the most important aspects of Numpy: vectors, arrays, matrices, and number generation.
At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:
1. NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
2. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of objects, thereby allowing for arrays of different sized elements.
3. NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
4. A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.


### Numpy Arrays¶
Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (note: a matrix can still have only one row or one column).
#### Creating NumPy Arrays¶
1.	From a Python List: We can create an array by directly converting a list or list of lists:

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

2.	By casting a list to numpy array

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[3,2,1],[4,6,5],[7,8,9]]
np.array(my_matrix)

array([[3, 2, 1],
       [4, 6, 5],
       [7, 8, 9]])

### There are lots of built-in ways to generate Arrays
1. arange: Return evenly spaced values within a given interval.
2. zeros and 
3. ones: Generate arrays of zeros or ones
4. linspace: Return evenly spaced numbers over a specified interval.
5. eye: Creates an identity matrix. Usually a square matrix useful in Linear algebra

In [5]:
#arange - Return evenly spaced values within a given interval 1 default when not specified.
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2) #Return evenly spaced values within a given interval, 2 specified.

array([ 0,  2,  4,  6,  8, 10])

In [7]:
#2. zeros - Generate arrays of zeros, shape given
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((5,5)) #Shape given 5x5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#4. linspace: Return evenly spaced numbers over a specified interval.
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0,10,50) #Returns 50 1D array of evenly spaced numbers from  0 - 10

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [13]:
#5. eye: Creates an identity matrix. Usually a square matrix useful in Linear algebra
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attributes and Methods
1. reshape - One of the most useful methods that could be used on an array is the reshape method. Reshape will return an array containing the same data type in new shape.
2. max - These are all useful methods for finding max or min values or to find their index locations using argmin or argmax
3. min
4. argmax
5. argmin
6. shape - Shape is an attribute that arrays have (not a method):
7. dtype - We can also grab the data type of the object in the array:

In [14]:
arr = np.arange(25) # Return a 1D array values between 0 and 24
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
ranarr = np.random.randint(0,50,10)  #Return an array of 10 random integers between 0 and 50
ranarr

array([ 1,  4,  4, 34, 47, 49, 10, 29, 38, 46])

In [16]:
# Will return a 5x5 2D array from the original array (arr). 
# Note that arr must have 25 members (5x5), else reshape will fail.
arr.reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
ranarr.max() #return the maximum value in ranarr

49

In [18]:
ranarr.min() #return the minimum value in ranarr

1

In [19]:
ranarr.argmin() #return the index location of min value in ranarr

0

In [20]:
ranarr.argmax() # return the index location of the max value in ranarr

5

In [21]:
# Will return a 5x5 2D array from the original array (arr). 
# Note that arr must have 25 members (i.e. rows of 5 x columns of 5 in this case), else reshape will fail.
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
# arr.reshape(5,3) --- This will FAIL

In [23]:
#Shape: Shape is an attribute that arrays have (not a method):
# Vector: 
arr.shape
# Notice here I get 25 comma and that's indicating that arr array was just a one dimensional vector.

(25,)

In [24]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [25]:
arr.reshape(1,25).shape   # (1, 25) returns a 1x25 array

(1, 25)

In [26]:
# arr.reshape(25,1)
arr.reshape(25,1).shape   # (25, 1) returns a - 25x1 array

(25, 1)

In [27]:
#arr.reshape(5,5)
arr.reshape(5,5).shape   # (5, 5) returns a - 5x5 array

(5, 5)

In [28]:
# You can also grab the data type of the object in the array:
arr.dtype

dtype('int32')

## ... Please NOTE:
#### Rather than saying import numpy.random as np 
#### We can use a smarter option as shown in this section, i.e.:
- from numpy.random import rand, randint, randn
- So, you may just use for example, randint(4,50) rather than the longer np.random.randint(4,50).[4]


# 2.    Simple random data
## 2.1.	Random¶
- Numpy also has lots of ways to create random number arrays:
